version: "3.5"
services:
  agile-helper-portal:
    image: nginx:1.13.6
    ports: 
      - 3001:80
    volumes: 
      - /home/agile-helper-portal-deploy/build:/usr/share/nginx/html
      - /home/agile-helper-portal-deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 2m
    networks:
      - uma-overlay
networks:
  uma-overlay:
